### ISSUE TITLE
Which Node framework do we want to use?

### ISSUE THREAD

**Issue by kratsg** [deafchi/signsfive-api#7]
Restify is great for a barebones but might have some performance issues. There are a few others we might want to look into based on benchmarking https://github.com/hbakhtiyor/node-frameworks-benchmark and https://raygun.com/blog/node-js-performance-2017/:

- [FeathersJs](https://docs.feathersjs.com/guides/about/readme.html)
- [total.js](https://www.totaljs.com/)

It's not 100% clear to what extent we really care about a lot of these issues, however restify is so barebones that it allows us to deal with all the other things. Maybe too barebones if we can't define a "resource" with CRUD out of the box (do we need that, really? maybe, if we just want our models to be as straightforward as possible)

**Comment by meltedspork** [comment]
@kratsg - Did we ever decided on this yet?

**Comment by kratsg** [comment]
I think we just decided on restify for now until we run into unforseen issues.

**Comment by meltedspork** [comment]
👍 closing this!
